#!/bin/zsh

SVN=${SVN_EXECUTABLE:-/usr/bin/svn}
COMMAND=$1
shift

# Parse command line
CMDLINE=
RC=$HOME/.svnrc
while [ -n "$1" ]; do
	if [[ "$1" =~ ^:.* ]]; then
		if [ -f $RC ]; then
			PROP=`echo $1 | cut -c2-`
			ARGS=`cat $RC | grep ^#${PROP}= | cut -d= -f2-`
			CMDLINE=$CMDLINE\ $ARGS
		fi
	else
		CMDLINE=$CMDLINE\ $1
	fi
	[ $# -gt 1 ] && shift || break
done

# Dispatch to external command plugin
if [ "$COMMAND" != "" ]; then
	PLUGIN_NAME=$(basename $0)-$COMMAND
	PLUGIN=$(command -v $PLUGIN_NAME)
	if [ "$PLUGIN" != "" ]; then
		#echo $LOG Dispatching to $PLUGIN
		eval SVN=$SVN $PLUGIN $CMDLINE
		exit 0
	fi
fi

#echo "[SVN] ${SVN}"
eval $SVN $COMMAND $CMDLINE
